### ISSUE TITLE
Default override behavior is reverse of python-dotenv

### ISSUE THREAD

**Issue by mahiki** [mpeteuil/poetry-dotenv-plugin#14]
The [default behavior of this plugin is to override the existing env variables](https://github.com/mpeteuil/poetry-dotenv-plugin/blob/b0c573aecf3ef4a2d78bfe11ad333b6890fc3f55/poetry_dotenv_plugin/dotenv_plugin.py#L32), unlike the default in python-dotenv.

As shown in the [python-dotenv docs](https://github.com/theskumar/python-dotenv), default is to not override env variables, in other words in python-dotenv the `.env` variables can be overridden by exporting a variable into the current environment.

With python-dotenv you can do `load_dotenv(override=True)` when you want `.env` file to override. Unfortunately, the poetry-dotenv doesn't allow the user to manage this aspect, its always going to override.

I think this is unexpected behavior for people who use python-dotenv.

Is there a way to set the poetry dotenv plugin to stop overriding existing environment variables?

**Comment by mpeteuil** [comment]
👋 Hello! The reason the default behavior of this plugin is what it is, is because [it has origins](https://github.com/python-poetry/poetry/issues/337) during the time when there were a lot of users migrating away from [Pipenv](https://github.com/pypa/pipenv), many switching to Poetry. [Pipenv had built-in `.env` loading](https://pipenv.pypa.io/en/latest/shell/#automatic-loading-of-env) which [did override by default (and still does)](https://github.com/pypa/pipenv/blob/98bdb5f8b2f08a435a825915d7d7d215a7aaec19/pipenv/utils/environment.py#L37). In order to support the many people coming from `pipenv` the goal was to make the fewest changes from that toolset possible in regards to `.env` loading. That is also why there are other some [analogous environment variables between this project and `pipenv` with a section about them in the README](https://github.com/mpeteuil/poetry-dotenv-plugin#coming-from-pipenv).

I agree that if you're coming from vanilla `python-dotenv` then this is unexpected. That needs to be reconciled with the expectations of anyone coming from `pipenv`. My proposal to resolve this is a system environment variable—`POETRY_DOTENV_DONT_OVERRIDE`—which is being added with #16. I think it should solve most cases. Most users who want it to [behave like `python-dotenv`'s defaults](https://github.com/theskumar/python-dotenv#getting-started) probably want that everywhere and the same for anyone who wants it to behave like `pipenv`.
