### ISSUE TITLE
Feature request: Variables in poetry shell too

### ISSUE THREAD

**Issue by StefanUlbrich** [mpeteuil/poetry-dotenv-plugin#8]
Hi! This is a very useful plugin. I wonder whether you can set the environment variables every time a `poetry shell` sesssion is spawned. I end up working a lot in activated environments

**Comment by StefanUlbrich** [comment]
Apologies! it does indeed work already. Visual studio code apparently directly activates the environment without consulting `poetry` at all :-( . The plugin works as one would expect. Good work!

**Comment by iTrooz** [comment]
Hey ! I'd like to get back to this problem, because I have the same one.
I use Visual Studio Code, and it loads the virtual environment automatically, without the environment variables
Then, even `poetry shell` won't add them, because I am already in the virtual environment

A couple of solutions I thought about, that would help this problem:
- somehow hook into the environment activation code to load the variables (idk how feasible it would be, and if it is even a good idea)
- Still add the environment variables when `poetry shell` is run, even if it says the environment is already loaded
- add another subcommand, like `poetry loadenv` (Seems the most reasonable solution)
